spring:
  application:
    name: anbd-api
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            scope:
              - profile
              - email

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-expiration-in-ms: ${ACCESS_EXPIRATION_IN}
  refresh-expiration-in-ms: ${REFRESH_EXPIRATION_IN}

server:
  port: 8080

gcs:
  bucket-name: ${BUCKET_NAME}
  credentials-path: ${SERVICE_ACCOUNTS_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
